twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  enable-mock-tweets: true
  mock-min-tweets: 5
  mock-max-tweets: 25
  mock-sleep-ms: 10000